### ISSUE TITLE
[Improvement]: [11th Oct - 15th Oct] Generate Open API Connectors

### ISSUE THREAD

**Issue by RolandHewage** [ballerina-platform/ballerina-extended-library#103]
### Connector Name

connectors/openapi (Open API Connector)

### Suggested improvement

Generate following connectors Using Open API to Ballerina tool. 

- [x] - [Dropbox](https://www.dropbox.com/developers/documentation/http/documentation)
- [x] - [Instagram](https://developers.facebook.com/docs/instagram-basic-display-api)
- [x] - [Paypal Payments](https://developer.paypal.com/docs/api/payments/v2/)

### Related issues

No response

**Comment by LakshanSS** [comment]
Closing since this is done
