### ISSUE TITLE
[Task]: Implement dailybuild workflow for Twitter connector

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-extended-library#12]
### Connector Name

module/twitter (Twitter)

### Task Description

Daily build implementation is missing in twitter connector repo
https://github.com/ballerina-platform/module-ballerinax-twitter

**Comment by LakshanSS** [comment]
Closing since this is done via https://github.com/ballerina-platform/module-ballerinax-twitter/pull/19
