### ISSUE TITLE
[Task]: Fix Salesforce Listener test case failure in SLBeta3

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-extended-library#13]
### Connector Name

module/salesforce (Salesforce)

### Task Description

$titile

**Comment by LakshanSS** [comment]
Closing since this issue is fixed by https://github.com/ballerina-platform/module-ballerinax-sfdc/pull/169

**Comment by LakshanSS** [comment]
The full details can be found here https://github.com/ballerina-platform/ballerina-lang/issues/32417
