### ISSUE TITLE
[Task]: Comparison with CDATA Connectors  

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-extended-library#136]
### Connector Name

other (None Listed Above)

### Task Description

We need to do a comparison of CData connectors vs the connectors we have. 

 - List down all the CData connectors
 - Mark the connectors we also have in that list
 - For the connectors we don't have, mark which of those systems have OpenAPI definitions or a HTTP API (mention which of them are available specifically)

Objective of this exercise is to see what are connectors we don't have and we can't easily generate from the list which CData has.

**Comment by SanduDS** [comment]
The comparison was done. Please find the relevant docs under the mail thread "Compare CData connectors vs Choreo connectors"
