### ISSUE TITLE
[Task]: Fix build issue related to G-Calendar listener

### ISSUE THREAD

**Issue by Chuhaa** [ballerina-platform/ballerina-extended-library#162]
### Connector Name

module/gcalendar (Google Calendar)

### Task Description

Fix daily build failure
https://github.com/ballerina-platform/module-ballerinax-googleapis.calendar/actions/runs/1479335877

**Comment by LakshanSS** [comment]
Closing since this is done via https://github.com/ballerina-platform/module-ballerinax-googleapis.calendar/pull/81
