### ISSUE TITLE
[Feature]: Implement the Ballerina types generator for GraphQL CLI tool

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-extended-library#178]
### Connector Name

other (None Listed Above)

### Task Description

The record types of the Generated Ballerina GraphQL client is dynamic. Each record will be generated according to the structure of the GraphQL queries the user provides in the `<file_name>.graphql` file. The data type of each field of the query must be obtained referring to the SDL.

### Following example scenarios shows the possible query patterns and structure of the intended record types
1. Query with a primitive type as variable

> Sample GraphQL query
> ```graphql
> query countryByCode($code: ID!) {
>     country(code: $code) {
>         name
>     }
> }
> ```
> Generated record type
> ```ballerina
> type CountryByCodeResponse record {|
>    record {|
>       string name;
>    |}? country;
>    map<json>? __extensions?;
> |};
> ```

2. Query with complex type as variable

> Sample GraphQL query
> ```graphql
> query countriesWithContinent($filter: CountryFilterInput) { 
>     countries(filter: $filter) {   
>         name
>         continent {
>             countries {
>                 name
>             }
>         }
>     }
> }
> ```

> Generated record type
> ```ballerina
> type CountriesWithContinentResponse record {|
>    record {|
>       string name;
>       record {|
>          record {|
>             string name;
>          |}[] countries;
>       |} continent;
>    |}[] countries;
>    map<json>? __extensions?;
> |};
> ```

3. Query with arguments

> Sample GraphQL query
> ```graphql
> query neighbouringCountries { 
>     countries(filter: {code: {eq: "LK"}}) {   
>         name
>         continent {
>             countries {
>                 name
>             }
>         }
>     }
> }
> ```

> Generated record type
> ```ballerina
> type NeighbouringCountriesResponse record {|
>    record {|
>       string name;
>       record {|
>          record {|
>             string name;
>          |}[] countries;
>       |} continent;
>    |}[] countries;
>    map<json>? __extensions?;
> |};
> ```

4. Query with fragments

> Sample GraphQL query
> ```graphql
> query MyFilms {
>   film(filmID: 1) {
>     title
>     director
>     speciesFirst: speciesConnection(first: 2) {
>       species {
>         ...SpeciesFields
>       }
>       totalCount
>     }
>     speciesLast: speciesConnection(last: 2) {
>       species {
>         ...SpeciesFields
>       }
>       totalCount
>     }
>   }
> }
> 
> fragment SpeciesFields on Species {
>   name
>   language
>   homeworld {
>     name
>   }
> }
> ```

> Generated record type
> ```ballerina
> type MyFilmsRecord record {|
>     record {|
>         string? title;
>         string? director;
>         record {|
>             record {|
>                 *SpeciesFieldsFragment;
>             |}?[]? species;
>         |}? speciesFirst;
>         record {|
>             record {|
>                 *SpeciesFieldsFragment;
>             |}?[]? species;
>        |}? speciesLast;
>     |}? film;
>     map<json>? __extensions?;
> |};
>  
> type SpeciesFieldsFragment record {|
>     string? name;
>     string? language;
>     record {|
>     string name;
>     |}? homeworld;
> |};
> ```

5.Query with inline fragments

> Sample GraphQL query
> ```graphql
> query MyFilm {
>   film(filmID: 1) {
>     ... on Film {
>       title
>       director
>     }
>     speciesConnection(first: 2) {
>       species {
>         ... on Species {
>           name
>           language
>         }
>         personConnection(first: 5) {
>           people {
>             ... on Person {
>               name
>               birthYear
>               gender
>             }
>           }
>         }
>       }
>       totalCount
>     }
>   }
> }
> ```

> Generated record type
> ```ballerina
> type MyFilmsRecord record {|
>     record {|
>         string? title;
>         string? director;
>         record {|
>             record {|
>                 string? name;
>                 string? language;
>                 record {|
>                     record {|
>                         string? name;
>                         string? birthYear;
>                         string? gender;
>                     |}?[]? people;
>                 |}? personConnection;
>             |}?[]? species;
>             int? totalCount;
>         |}? speciesConnection;
>     |}? film;
>     map<json>? __extensions?;
> |};
> ```

> Sample GraphQL query
> ```graphql
> query MyPokeman {
>   allPokemon(limit: 10) {
>     name
>     evolution_criteria {
>       ... on Move {
>         description
>         power
>         accuracy
>       }
>       ... on Location {
>         region {
>           name
>         }
>       }
>       ... on Gender {
>         id
>       }
>       ... on OtherEvolutionCriteria {
>         value
>       }
>       ... on Item {
>         effect
>         id
>       }
>       ... on Type {
>         double_damage_from {
>           id
>         }
>       }
>     }
>   }
> }
> ```

> Generated record type
> ```ballerina
> type MyPokemanRecord record {|
>     record {|
>         string name;
>         record {|
>             string description;
>             int power;
>             int accuracy;
>             record {|
>                 string name;
>             |} region;
>             string id;
>             string effect;
>             string value;
>             record {|
>                 string id;
>             |} double_damage_from;
>         |}[] evaluation_criteria;
>     |}[] allPokeman;
>     map<json>? __extensions?;
> |};
> ```

6. Query with aliases

> Sample GraphQL query
> ```graphql
> query myFilms {
>   film1characters: film(filmID: 1) {
>     characterConnection(first: 5) {
>       characters {
>         name
>       }
>     }
>   }
>   film2characters: film(filmID: 2) {
>     characterConnection(first: 5) {
>       characters {
>         name
>       }
>     }
>   }
> }
> ```

> Generated record type
> ```ballerina
> type MyFilmsRecordw record {|
>     record {|
>         record {|
>             record {|
>                 string name;
>             |}[] characters;
>         |} characterConnection;
>     |} film1characters;
>     record {|
>         record {|
>             record {|
>                 string name;
>             |}[] characters;
>         |} characterConnection;
>     |} film2characters;
>     map<json>? __extensions?;
> |};
> ```

### The decisions in the design reviews
- The record types for queries must be generated as inline records to eliminate the possibility of large number of repetitions if the records are created using the `Object Type Definitions`.
- `Input Type Definitions` will be generated as it is according to the [mapping between GraphQL `Type Definitions` and ballerina](https://docs.google.com/document/d/1bw0HKHhAT4R3HujWtJoX3Q9D37h6H4k6DsMH8s9fVnk/edit#heading=h.ih7i4v7jv49c).
- All the record types related to each `<file_name>.graphql` file related to one project will be generated in single types.bal file.

**Comment by abeykoon** [comment]
@LakshanSS please link the relevant PR on to this issue. 
AFAIR, we reviewed the implementation too.

**Comment by LakshanSS** [comment]
https://github.com/RolandHewage/graphql-tools/tree/temp_integration has the latest code.
