### ISSUE TITLE
[Task]:  Market research on SAP connectors

### ISSUE THREAD

**Issue by SanduDS** [ballerina-platform/ballerina-extended-library#234]
### Connector Name

other (None Listed Above)

### Task Description

Conducting market research on SAP connectors and their technologies used.

**Comment by abeykoon** [comment]
@SanduDS is there a doc with findings?

**Comment by SanduDS** [comment]
@abeykoon  Please refer [this doc ](https://docs.google.com/spreadsheets/d/1I0wg85sRVAt0XuNY33asgYz_qyHdrXXIRVEQ6GZ5pzM/edit?usp=sharing)for the findings.
