### ISSUE TITLE
Anti-pattern Ballerina codes in the extended libraries

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-extended-library#264]
**Description:**
I've noticed many extended libraries have the Ballerina anti-pattern codes. Better to remove those anti-patterns according to [this doc](https://docs.google.com/document/d/1y6QVqaZzZt9jMpYV4jP5WRS_W_KoC4y40Uuoh1ALu8E/edit#heading=h.kel062m2vr8k).

E.g: Unnecessary parenthesis
- https://github.com/ballerina-platform/module-ballerinax-slack/blob/ce6b95dcba6a003104ba8feb6c156effb40d3eba/slack/utils.bal#L71
- https://github.com/ballerina-platform/module-ballerinax-sfdc/blob/3595156e5d881670eca65c074846af3f946d4076/salesforce/rest_utils.bal#L54

**Comment by abeykoon** [comment]
@sachinira shall we fix both in master branch?

**Comment by abeykoon** [comment]
@BuddhiWathsala with code reviews with Ballerina team, they did not complain on using if,else with additional parenthesis. Is it something imposed lately? There will be a tons of places where we will have to alter across the libraries.

**Comment by sachinira** [comment]
> @sachinira shall we fix both in master branch?

ack

**Comment by BuddhiWathsala** [comment]
> @BuddhiWathsala with code reviews with Ballerina team, they did not complain on using if,else with additional parenthesis. Is it something imposed lately? There will be a tons of places where we will have to alter across the libraries.

This is a recent attempt we made for stdlibs based on the guidelines in the above doc https://github.com/ballerina-platform/ballerina-standard-library/issues?q=is%3Aissue+code+quality+is%3Aclosed

**Comment by abeykoon** [comment]
Closing as Fixed.
