### ISSUE TITLE
[Docs]: API documents for Azure storage connector could not be found

### ISSUE THREAD

**Issue by nilushancosta** [ballerina-platform/ballerina-extended-library#274]
### Connector Name

module/azure-storageservice (Azure Blob & Storage Service)

### Documentation Issue/Improvement

In https://lib.ballerina.io/ballerinax, the API document links for the following 3 connectors result in `404: This page could not be found.` errors

<img width="1294" alt="Screenshot 2022-02-03 at 17 52 56" src="https://user-images.githubusercontent.com/19643850/152342227-78a8cbfd-5bc7-4d73-9e5c-216c8a25f535.png">

**Comment by LakshanSS** [comment]
Latest API doc can be found here: https://lib.ballerina.io/ballerinax/azure_storage_service/latest
