### ISSUE TITLE
[Improvement]: [Redis] Convert as a gradle project

### ISSUE THREAD

**Issue by LakshanSS** [ballerina-platform/ballerina-extended-library#31]
### Connector Name

module/redis (Redis)

### Suggested improvement

Currently it is a maven project. Need to convert it to gradle.

**Comment by aneeshafedo** [comment]
Closing issue since this is done via ballerina-platform/module-ballerinax-redis#165

**Comment by aneeshafedo** [comment]
Closing issue since this is done via ballerina-platform/module-ballerinax-redis#165
