### ISSUE TITLE
[Bug]: Fixing broken samples / enabling disabled samples

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-extended-library#319]
### Connector Name

other (None Listed Above)

### What happened?

Here is a list of samples which was disabled due to an issue `http:OAuth2RefreshTokenGrantConfig` used inside the samples.
(More details https://github.com/ballerina-platform/ballerina-lang/issues/34417#issuecomment-1011797446)

> gcalendar_to_twilio'
github_new_commit_to_google_sheet_row'
sfdc_outbound_msg_to_gsheet'
twilio_new_sms_to_gmail_inbox'
twilio_sms_to_gsheet'
gdrive_new_file_to_gsheet_rows'
gmail_new_attachment_to_drive'
gdrive_new_file_to_twilio_sms'

Remove the usage of `http:OAuth2RefreshTokenGrantConfig` record and use below custom record as the configurable
```bal
type OAuth2RefreshTokenGrantConfig record {
    string clientId;
    string clientSecret;
    string refreshToken;
    string refreshUrl;
};
```

**Comment by LakshanSS** [comment]
I think this issue is fixed via https://github.com/wso2-enterprise/choreo-samples/pull/451
