### ISSUE TITLE
[Improvement]: [Redis] Need to use ballerina action instead of ballerina zip distribution in the github build workflows

### ISSUE THREAD

**Issue by LakshanSS** [ballerina-platform/ballerina-extended-library#33]
### Connector Name

module/redis (Redis)

### Suggested improvement

Currently we use the ballerina zip distribution in the github build workflows.
Need to use [ballerina action](https://github.com/ballerina-platform/ballerina-action) instead of ballerina zip distribution.

This improvement is blocked until we fix https://github.com/ballerina-platform/ballerina-extended-library/issues/32

**Comment by abeykoon** [comment]
@kapilraajP what about doing the change in the Redis connector so that we can resolve this issue.

**Comment by aneeshafedo** [comment]
Closing since this has been addressed via ballerina-platform/module-ballerinax-redis#170
