### ISSUE TITLE
[Bug]: Fixing issues in disabled Choreo samples

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-extended-library#335]
### Connector Name

connectors/samples (Connector Samples/Templates)

### What happened?

There are 22 samples that are hidden on Choreo due to various issues on them.

We need to identify all issues, group the issues accordingly, and fix them.

<google-sheets-html-origin><style type="text/css"></style>

Disabled samples
--
github_issue_summary_to_email'
gcalendar_to_twilio'
github_new_commit_to_google_sheet_row'
sfdc_outbound_msg_to_gsheet'
twilio_new_sms_to_gmail_inbox'
twilio_sms_to_gsheet'
gdrive_new_file_to_gsheet_rows'
gmail_new_attachment_to_drive'
gdrive_new_file_to_twilio_sms'
json_to_xml_conversion'
xml_navigation'
circuit_breaker'
github_issue_assigned_to_sms'
github_issue_assigned_to_twilio_sms'
github_new_release_to_twilio_sms'
github_release_to_slack'
gsheet_new_row_to_github_new_issue'
gsheet_new_row_to_sfdc_new_lead'
gsheet_new_row_to_sfdc_new_record'
gsheet_row_update_to_gmail'
gsheet_update_row_to_sfdc_update_record'
slack_new_message_to_twilio_sms'

**Comment by SkNuwanTissera** [comment]
Related issues 
https://github.com/wso2-enterprise/choreo/issues/11797
https://github.com/wso2-enterprise/choreo/issues/11798
https://github.com/wso2-enterprise/choreo/issues/11800
https://github.com/wso2-enterprise/choreo/issues/11801
https://github.com/wso2-enterprise/choreo/issues/11802
https://github.com/wso2-enterprise/choreo/issues/11803
https://github.com/wso2-enterprise/choreo/issues/11805
https://github.com/wso2-enterprise/choreo/issues/11803
https://github.com/wso2-enterprise/choreo/issues/11806
https://github.com/wso2-enterprise/choreo/issues/11850

**Comment by SkNuwanTissera** [comment]
All samples are now enabled except `circuit_breaker` [1] 

[1] https://github.com/wso2-enterprise/choreo/issues/11850

Issue can be closed after enabling [1]

**Comment by LakshanSS** [comment]
Closing since its fixed via https://github.com/wso2-enterprise/choreo/issues/11850
