### ISSUE TITLE
[Improvement]: Add `Interzoid weather updates to Slack New Message` 

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-extended-library#373]
### Connector Name

connectors/samples (Connector Samples/Templates)

### Connector Name

connectors/samples (Connector Samples/Templates)

### Suggested improvement

This sample can be configured to send weather updates to a specified Slack channel periodically.

![image](https://user-images.githubusercontent.com/19235998/164380606-5828025f-6221-46e5-aaed-f399e24b8d08.png)

The message (on slack) will be displayed below.

![image](https://user-images.githubusercontent.com/19235998/164701409-ed3d875b-91bf-41ab-8bb1-95981d5dff8e.png)

### Related issues

I am trying to do [...] but [...]

**Comment by LakshanSS** [comment]
Closing since this was done via https://github.com/wso2-enterprise/choreo-samples/pull/489
