### ISSUE TITLE
[Bug]: Github Client Error

### ISSUE THREAD

**Issue by viradhanus** [ballerina-platform/ballerina-extended-library#374]
### Connector Name

module/github (Github)

### What happened?

I execute the following code (in Choreo) and it's a  **simple code** to print (log) the repository count of a given organization. 

import ballerinax/github;
import ballerina/http;
import ballerina/log;

map<string|string[]> headers = {
    "Access-Control-Allow-Headers": "authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction,Authorization,jwt,API-Key",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, DELETE, PUT, OPTIONS"
};

service /bug on new http:Listener(9090) {

    resource function post addRepo/[string orgName]() returns http:Ok|error {

        github:Client githubEndpoint = check new ({auth: {token: "MY_TOKEN"}});
        stream<github:Repository, error?> getRepositoriesResponse = check githubEndpoint->getRepositories(orgName, true);
        int count = 0;
        error? e = getRepositoriesResponse.forEach(function(github:Repository repository) {
            count += 1;
            log:printInfo(count.toString());
        });

        if (e is error) {
            log:printInfo(e.message());
            return e;
        } else {
            log:printInfo("Success!");
            http:Ok response = {
                body: {
                    "data": count.toString()
                },
                headers: headers
            };
            return response;
        }

    }
}

Here the code is working fine for a organizations with less number of repositories (ideally less than 100) but it gives the following error and stop executing for a organizations with large number of repositories (Ex: OWASP). Furthermore, the execution interrupts in random (**100x**) counts. 

#### Stops at count = 500
<img width="960" alt="at500" src="https://user-images.githubusercontent.com/59219626/164773619-5d8bb9f9-8cdc-4100-91fd-20b32b5b8580.PNG">

#### Stops at count = 700
<img width="960" alt="at700" src="https://user-images.githubusercontent.com/59219626/164773718-21acb10a-af79-430d-9254-4ac5fb8b0cd0.PNG">

**Comment by kasthuriraajan** [comment]
This is not an issue in the connector. It happens from GitHub's server side while timeout happening for a big result. If you use proper retry mechanism when you expect a big set of result , the problem will be resolved.
