### ISSUE TITLE
[Improvement]: Provide pagination support for List and Query operations in Salesforce connector

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-extended-library#377]
### Connector Name

module/salesforce (Salesforce)

### Suggested improvement

The pagination of Salesforce responses are not handled internally in the Salesforce connector. In the current approach users can call the  `getQueryResult` operation to get the first page only. Then he has to call the `getNextQueryResult` operation by passing the `nextRecordsUrl` obtained from the previous call as a parameter and obtain the subsequent pages.

The fix will contain implementing Ballerina stream implementer to handle the second call on demand internally without user intervention.

**Comment by abeykoon** [comment]
This is on production central now. Older syntax is there, but they are deprecated. 
We will remove them in the next iteration. 

<img width="849" alt="image" src="https://user-images.githubusercontent.com/4967046/167331243-a7cf0691-eaac-4b6b-8bda-438984133fab.png">
