### ISSUE TITLE
[Bug]: Fix intermittent build failure `Microsoft.outlook.calendar`

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-extended-library#382]
### Connector Name

module/outlook-calendar (Outlook Calendar)

### What happened?

Daily build fails intermittently. Should find the reason & do a fix.

### Relevant log output

```shell
https://github.com/ballerina-platform/module-ballerinax-microsoft.outlook.calendar/runs/6187263417?check_suite_focus=true
```

**Comment by LakshanSS** [comment]
Closing since this is fixed via https://github.com/ballerina-platform/module-ballerinax-microsoft.outlook.calendar/pull/28
