### ISSUE TITLE
[Improvement]: Get context information of a commits in a pull requests

### ISSUE THREAD

**Issue by viradhanus** [ballerina-platform/ballerina-extended-library#391]
### Connector Name

module/github (Github)

### Suggested improvement

This feature is already available in the Github GraphQL API. An example code to get context information of a latest commit in a latest `OPEN` pull request is as follows. 

`
{
  repository(owner: "jwo", name: "react-hover-image") {
    url
    pullRequests(last: 1, states: [OPEN]) {
      nodes {
        commits(last: 1) {
          nodes {
            commit {
              commitUrl
              oid
              status {
                contexts {
                  state
                  targetUrl
                  description
                  context
                }
              }
            }
          }
        }
      }
    }
  }
}
`

The result of the above code is as follows.

`
{
  "data": {
    "repository": {
      "url": "https://github.com/jwo/react-hover-image",
      "pullRequests": {
        "nodes": [
          {
            "commits": {
              "nodes": [
                {
                  "commit": {
                    "commitUrl": "https://github.com/jwo/react-hover-image/commit/f5559bb1a2e3eec532e67147ba2de0d292afb146",
                    "oid": "f5559bb1a2e3eec532e67147ba2de0d292afb146",
                    "status": {
                      "contexts": [
                        {
                          "state": "SUCCESS",
                          "targetUrl": "https://codeclimate.com/github/jwo/react-hover-image/pull/38",
                          "description": "All good!",
                          "context": "codeclimate"
                        }
                      ]
                    }
                  }
                }
              ]
            }
          }
        ]
      }
    }
  }
}
`

### Related issues

Currently, I am creating a Cloud Security Status Monitoring Tool as my intern project at WSO2. Here I need to display the status of the each pipeline used in a repository including the context information.

**Comment by LakshanSS** [comment]
Closing since this is done via https://github.com/ballerina-platform/module-ballerinax-github/pull/219
