### ISSUE TITLE
[Feature] [Data-Explorer]: Implement configurable editor for the data explorer

### ISSUE THREAD

**Issue by RolandHewage** [ballerina-platform/ballerina-extended-library#399]
### Connector Name

other (None Listed Above)

### Suggested feature

Implement configurable editor for the data explorer to popup a config editor when the `Explore` button is clicked if any configurable variables are present.

**Comment by RolandHewage** [comment]
It was decided to reuse the existing configurable editor implementation in the vs-code plugin. Therefore assigning Aneesha to proceed.

**Comment by aneeshafedo** [comment]
Decided to re-visit the design of the Choreo Data Explorer, therefore closing the issue
