### ISSUE TITLE
[Bug]: Github Client getIssues Error

### ISSUE THREAD

**Issue by prakanth97** [ballerina-platform/ballerina-extended-library#413]
### Connector Name

module/github (Github)

### What happened?

I execute the following code to get the issues count in standard-library repo by applying filters.
```
function getIssuesCount(string repoName, string shortName) returns int|error? {
    stream<github:Issue, github:Error?> issues = check githubClient->getIssues("ballerina-platform", "ballerina-standard-library", issueFilters = {labels: ["Type/Bug", "module/io"], states: [github:ISSUE_OPEN]});
    issueCount = 0;
    _ = check issues.forEach(count);
    return issueCount;
}

function count(github:Issue issue) {
    issueCount += 1;
}
```

Required output filter should be like this `is:issue is:open label:Type/Bug label:module/io`(https://github.com/ballerina-platform/ballerina-standard-library/issues?q=is%3Aissue+is%3Aopen+label%3AType%2FBug+label%3Amodule%2Fio+). But it gave me the output of `is:issue is:open label:Type/Bug,module/io` (https://github.com/ballerina-platform/ballerina-standard-library/issues?q=is%3Aissue+is%3Aopen+label%3AType%2FBug%2Cmodule%2Fio+). 

I could not find a way to pass required filter in the `labels`.

**Comment by LakshanSS** [comment]
@kasthuriraajan I guess we can do this by the `search` operation than going for the `getIssues` operation right?

**Comment by kasthuriraajan** [comment]
Yes @LakshanSS  you are correct. Here `search` operation is the recommended way. `getIssues` operation has some limitations. 
@prakanth97 for your use case you can use the following code which uses the `search` operation.
```
    string searchQuery = "repo:ballerina-platform/ballerina-standard-library is:issue is:open label:Type/Bug label:module/io";
    github:SearchResult result = check githubClient->search(searchQuery, github:SEARCH_TYPE_ISSUE, 100);

    int issueCount = result.issueCount;
```
