### ISSUE TITLE
[Improvement]: Add openapi connector `ballerinax/amadeus.flightoffersprice`

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-extended-library#416]
### Connector Name

connectors/openapi (Open API Connector)

### Suggested feature

Add openapi connector `ballerinax/amadeus.flightoffersprice` [1] 

[1] https://developers.amadeus.com/self-service/category/air/api-doc/flight-offers-price

### Related issues

I am trying to do [...] but [...]

**Comment by LakshanSS** [comment]
Closing since this is done
