### ISSUE TITLE
[Task]: Extract useful enterprise level integration scenarios from Celigo

### ISSUE THREAD

**Issue by RolandHewage** [ballerina-platform/ballerina-extended-library#419]
### Connector Name

other (None Listed Above)

### Task Description

There are some good enterprise level integration scenarios with a research background in [Celigo](https://www.celigo.com). We need to identify these scenarios. They can be used to build valuable Choreo integration samples.

**Comment by abeykoon** [comment]
Compiled doc (not accessible outside): 
https://docs.google.com/spreadsheets/d/15mMM0RocwAoEYIKPFYjgk2guAom8d7V1sP_HV0aO6Jw/edit?usp=sharing

**Comment by RolandHewage** [comment]
Some useful enterprise level integration scenarios extracted from Celigo (https://www.celigo.com/) and summarized in above doc. We can use them when implementing new Choreo samples in the future. Therefore closing this issue.
