### ISSUE TITLE
[Improvement]: Allow to add request headers when creating containers

### ISSUE THREAD

**Issue by AyeshW** [ballerina-platform/ballerina-extended-library#432]
### Connector Name

module/azure-storageservice (Azure Blob & Storage Service)

### Suggested improvement

Add capability to get header/values pairs when creating containers. In my case, I need to create containers with `x-ms-blob-public-access` header.
https://docs.microsoft.com/en-us/rest/api/storageservices/create-container#request-headers

### Related issues

I am trying to do creating public containers with azure storage service connector but it does not support for adding headers to the container creation method. Therefore, all the containers are created with default private access.

**Comment by abeykoon** [comment]
@Chuhaa will have a look on this.

**Comment by Chuhaa** [comment]
This has been fixed in 2.2.4 version and available in prod.
![image](https://user-images.githubusercontent.com/24509926/172376102-f99a869d-49a9-45a3-9c2b-9244357fa2ba.png)
