### ISSUE TITLE
[Improvement]: Improve Github connector to search for PRs 

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-extended-library#448]
### Connector Name

module/github (Github)

### Suggested improvement

* I need to search for PRs with a date range raised by a specific person 
* What is the operation I can use? 
* I should be able to get basic information about the PR like - date, raised by, repository, lines of codes/files modified, status of the PR etc

### Related issues

I tried to look for an available operation. Not sure if `Search` can be used for this.

**Comment by sachinira** [comment]
We can use the `search` operation for this. It has the ability to search PRs according to the necessary criteria. But, currently for the PR searches the data binding is not enabled in the connector and it could lead to intermittent data binding failures. 
Eg: 
For query 
```
repo:ballerina-platform/ballerina-extended-library is:pr is:open
```
The data binding passes

For query 
```
repo:ballerina-platform/ballerina-extended-library is:pr state:closed author:abeykoon created:2021-11-01..2022-07-11
```
The data binding fails

This needs to be improved in the connector
