### ISSUE TITLE
Webhook listener seems to support only one service?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-extended-library#45]
**Description:**
Noticed in the code that a listener seems to assume that is only one service attached to it - https://github.com/ballerina-platform/module-ballerinax-github/blob/master/github/modules/webhook/listener.bal#L32.

But it is possible for multiple services to attach to a single listener.

```ballerina
import ballerinax/github.webhook;

listener webhook:Listener ln = new (8080);

service "s1" on ln {
    
}

service "s2" on ln {
    
}
```

Shouldn't multiple services be supported?

Or at least, shouldn't this result in an error? Multiple calls to Listener.attach (which is what gets called per attached service), seems to silently overwrite the existing service - https://github.com/ballerina-platform/module-ballerinax-github/blob/master/github/modules/webhook/listener.bal#L63.

**Comment by abeykoon** [comment]
@sachinira shall we check on this. I know that we are going to get rid of listeners soon, but wish to understand more.

**Comment by sachinira** [comment]
Ack

**Comment by abeykoon** [comment]
@MaryamZi - we removed all listeners from client packages (i.e connectors), so this issue is not valid anymore.
