### ISSUE TITLE
[Bug]: The Salesforce trigger login request is not working when using Sandbox environments

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-extended-library#451]
### Connector Name

module/salesforce (Salesforce)

### What happened?

When trying to use the Salesforce trigger with the credentials of a Sandbox environment the execution provides a login error. 

### Relevant log output

```shell
error: Unable to login: INVALID_LOGIN: Invalid username, password, security token; or user locked out.
        at ballerinax.trigger.salesforce.0:startListener(listener.bal:93)
           ballerinax.trigger.salesforce.0.Listener:start(listener.bal:57)
```

**Comment by sahanHe** [comment]
Hi,
When tried to implement the following choreo example, [sfdc-new-lead-to-twilio-sms](https://github.com/wso2-enterprise/choreo-samples/blob/main/samples/integrations/sfdc-new-lead-to-twilio-sms/Package.md), I facing the same issue with following error message.
```
error: Unable to login: INVALID_LOGIN: Invalid username, password, security token; or user locked out.
        at ballerinax.trigger.salesforce.0:startListener(listener.bal:91)
           ballerinax.trigger.salesforce.0.Listener:start(listener.bal:55)
```

Can you kindly take a look in to this issue.

Regards,
Sahan

**Comment by sachinira** [comment]
> Hi, When tried to implement the following choreo example, [sfdc-new-lead-to-twilio-sms](https://github.com/wso2-enterprise/choreo-samples/blob/main/samples/integrations/sfdc-new-lead-to-twilio-sms/Package.md), I facing the same issue with following error message.
> 
> ```
> error: Unable to login: INVALID_LOGIN: Invalid username, password, security token; or user locked out.
>         at ballerinax.trigger.salesforce.0:startListener(listener.bal:91)
>            ballerinax.trigger.salesforce.0.Listener:start(listener.bal:55)
> ```
> 
> Can you kindly take a look in to this issue.
> 
> Regards, Sahan

Ack will update the trigger
