### ISSUE TITLE
[Improvement]: Get support for Github 'Create or update an organization/repository secret'

### ISSUE THREAD

**Issue by IsuruBoyagane15** [ballerina-platform/ballerina-extended-library#47]
### Connector Name

module/github (Github)

### Suggested improvement

Currently Ballerina Github connector does not support this API to  `create or update an organization/repository secret`.
Can we have get this APIs supported for ballerina Github connector.

This API expects the the secrets to be set to be encrypted using [Libsodium](https://libsodium.gitbook.io/doc/) encryption libraray.

This encryption is also not supported by Ballerina at the moment and will be addressed with this [issue](https://github.com/ballerina-platform/ballerina-standard-library/issues/1905).

### Related issues

A Choreo service (https://github.com/wso2-enterprise/choreo/issues/7145) implemented in Ballerina got the requirement to call this API (https://docs.github.com/en/rest/reference/actions#create-or-update-a-repository-secret). But since it is not supported at the moment, an http:CLient was used.

**Comment by abeykoon** [comment]
@kasthuriraajan can you please check the feasibility of this? 
Should we wait for Ballerina feature? Or for connector, can somebody give the secret as plain text?

**Comment by kasthuriraajan** [comment]
@abeykoon I'll investigate this.

**Comment by shafreenAnfar** [comment]
@ldclakmal can we do the encryption in Ballerina ?

**Comment by ldclakmal** [comment]
> @ldclakmal can we do the encryption in Ballerina ?

Yes we can. But for this particular requirement we need to support Sodium encryption.

**Comment by shafreenAnfar** [comment]
> Yes we can. But for this particular requirement we need to support Sodium encryption. There is a separate issue [1] created as well.

I think it is not part of the standard library of any programming language. I think it should be an external library.  Is that correct ?

**Comment by ldclakmal** [comment]
As per the libsodium documentation [1], it is supported by only few standard libraries. But for programming languages like Go, Python, Rust it is an external library. Go - Crypto library [2], Python - PyNaCl library [3] and Rust - sodiumoxide library [4] are some of the popular external libraries.

[1] https://libsodium.gitbook.io/doc/bindings_for_other_languages
[2] https://pkg.go.dev/golang.org/x/crypto
[3] https://pynacl.readthedocs.io/en/latest/
[4] https://docs.rs/sodiumoxide/latest/sodiumoxide/

**Comment by kasthuriraajan** [comment]
At the moment this API is only available in GitHub Rest API. But our connector is using GitHub GraphQL API. GraphQL API doesn't support this feature. So we could not fix it now.
