### ISSUE TITLE
[Feature]: Item Group Insertion Support for Netsuite Connector

### ISSUE THREAD

**Issue by DSKottachchi** [ballerina-platform/ballerina-extended-library#473]
### Connector Name

module/netsuite (Netsuite)

### Suggested feature

The Netsuite connector should support the insertion of item groups to a Netsuite invoice 

### Related issues

Currently the Netsuite connector only supports the insertion of main items and there is no support to add sub list items (items within item groups) to a Netsuite invoice.

Email Thread: [ballerinax/netsuite] Sub-list Item Support for Invoices in Netsuite

**Comment by LakshanSS** [comment]
Closing since this is done via https://github.com/ballerina-platform/module-ballerinax-netsuite/pull/79
