### ISSUE TITLE
[Bug]: Resolve Daily build failures of Salesforce connector

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-extended-library#478]
### Connector Name

module/salesforce (Salesforce)

### What happened?

Some of the daily builds for Salesforce connector was failing. 

Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/38609

**Comment by LakshanSS** [comment]
Closing since the salesforce daily build failures are now fixed via 
- https://github.com/ballerina-platform/module-ballerinax-sfdc/pull/276
- https://github.com/ballerina-platform/module-ballerinax-sfdc/pull/277
- https://github.com/ballerina-platform/module-ballerinax-sfdc/pull/278
