### ISSUE TITLE
[Task]: Update connectors to Ballerina version 2201.3.1

### ISSUE THREAD

**Issue by SanduDS** [ballerina-platform/ballerina-extended-library#483]
### Connector Name

other (None Listed Above)

### Task Description

The following connectors will be updated to the Ballerina version **2201.3.1**
This is related to the issue https://github.com/wso2-enterprise/choreo/issues/17626
1. [Twitter](https://github.com/ballerina-platform/module-ballerinax-twitter/pull/87) 
2. [NetSuite](https://github.com/ballerina-platform/module-ballerinax-netsuite/pull/86)

**Comment by LakshanSS** [comment]
Closing since the above connectors are released
