### ISSUE TITLE
[Improvement]: Update the connector to fix the daily build failures

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-extended-library#485]
### Connector Name

module/microsoft-onedrive (MS OneDrive)

### Suggested improvement

$subject

### Related issues

I am trying to do [...] but [...]

**Comment by LakshanSS** [comment]
This issue was fixed by the following PRs. Hence closing this issue
https://github.com/ballerina-platform/module-ballerinax-microsoft.onedrive/pull/60
https://github.com/ballerina-platform/module-ballerinax-microsoft.onedrive/pull/61
