### ISSUE TITLE
[Feature]: Employee Custom Screen

### ISSUE THREAD

**Issue by chanukaranaba** [ballerina-platform/ballerina-extended-library#486]
### Connector Name

module/peoplehr (People HR)

### Suggested feature

We have requirement to get custom screen data of an employee.

This is the API Support from People HR [[1](https://apidocs.peoplehr.com/#tag/Employee-Custom-Screen)] 
Following are the method required.

<img width="316" alt="Screenshot 2023-01-13 at 3 21 48 PM" src="https://user-images.githubusercontent.com/3981543/212291407-51658de8-97fa-4f24-bfe6-1c1a134d74a1.png">

[1] [https://apidocs.peoplehr.com/#tag/Employee-Custom-Screen](https://apidocs.peoplehr.com/#tag/Employee-Custom-Screen)

**Comment by SanduDS** [comment]
Closing as done
