### ISSUE TITLE
[Bug]: Salesforce query method returns an unknown (null) data type 

### ISSUE THREAD

**Issue by yuk7hi** [ballerina-platform/ballerina-extended-library#489]
### Connector Name

module/salesforce (Salesforce)

#### Description
The Salesforce (SF) client `query` method always returns an unknown (null) data type instead of returning `stream` or `error` types. This assigned value is not identified in Ballerina, and trying to use the given value anywhere (Eg: trying to print the value) throws a Java exception.

Refer to the sample code below:
```ballerina
    string query = string `SELECT Id FROM Lead`;
    stream<record{}, error?>|error sfResult = sfEp->query(query);
    io:println(sfResult);
```

#### OS, DB, other environment details and versions
- Ballerina Swan Lake 2201.3.2 (Update 3)
- ballerinax/salesforce 7.2.0

### Relevant log output

```shell
error: java.lang.NullPointerException
	at ballerina.lang.error.0:toString(error.bal:124)
	   ballerina.io.1.PrintableClassImpl:toString(print.bal:109)
	   ballerina.io.1:externPrintln(print.bal:147)
	   ballerina.io.1:println(print.bal:65)
	   test:main(test.bal:45)
```

**Comment by LakshanSS** [comment]
Closing since this was fixed via https://github.com/ballerina-platform/module-ballerinax-sfdc/pull/276
Choreo issue: https://github.com/wso2-enterprise/choreo/issues/17969

Released a patch `ballerinax/salesforce 7.2.1 with the fix`
