### ISSUE TITLE
[Bug]: [CosmosDB] replaceDocument function fails with a document that contains a JSON-unfriendly string

### ISSUE THREAD

**Issue by LakshanSS** [ballerina-platform/ballerina-extended-library#508]
### Connector Name

module/cosmosdb (Cosmos DB)

### What happened?

This is reported via Discord https://discord.com/channels/957996897782616114/1108861656316002335/1108861656316002335

### Relevant log output

```shell
error: Illegal unquoted character ((CTRL-CHAR, code 10))
```

**Comment by sachinira** [comment]
The issue with JSON-unfriendly string can be resolved by **escaping** the special characters such as `\n`. 

![Screenshot from 2023-05-30 17-21-55](https://github.com/ballerina-platform/ballerina-extended-library/assets/34184297/5ecc8dfd-c4ce-4bc6-8dd0-aef3f72f0022)

Optionally, we can **Base64 encode** the specific data and insert it in the document or if the JSON-unfriendly string is large we can go to an option like storing the string in a separate attachment and refer it in the document.

- We cannot replace the `id` as per the current implementation of the connector.

- The option to replace the `_etag` is also not supported as per the current implementation of the connector. We have to check if this is possible to do with our native implementation. This option is supported in [CosmosDB SDKs](https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/blob/main/src/main/java/com/azure/cosmos/examples/documentcrud/sync/DocumentCRUDQuickstart.java#L210)

**Comment by sachinira** [comment]
We can send an `_etag` of our choice in the document body but, CosmosDB replaces this with an auto generated `_etag` of it's own. If we try to do this via their data explorer the result is same. So this requirement is not possible at the moment
