### ISSUE TITLE
[Improvement]: Add GraalVM Checks for BallerinaX Modules

### ISSUE THREAD

**Issue by AzeemMuzammil** [ballerina-platform/ballerina-extended-library#512]
### Connector Name

other (None Listed Above)

### Suggested improvement

Add GrallVM checks for Daily Build and PR Builds for all Ballerina-Extended repositories.
Use this doc to track the progress: https://docs.google.com/spreadsheets/d/1_apEJLq7mLyB_P33I_FxzWE2flv08uJ85Yb2VP5y2aY

**Comment by NipunaRanasinghe** [comment]
Reopening as the issue as we still have a few remaining modules to be verifed

**Comment by NipunaRanasinghe** [comment]
Closing as completed
