### ISSUE TITLE
[Feature]: Introduce a receiver client API to retrieve messages from the dead letter queue

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-extended-library#517]
### Connector Name

module/azure-servicebus (Azure Servicebus)

### Suggested feature

Right now there's no way to read the dead-lettered messages in ASB using our existing client. We should be able to implement this directly, as the ASB java SDK we are using seems to be having this capability already.

**Comment by kapilraajP** [comment]
This can be achieved by using the receiver client by inputting dead letter queue namespace in the receiver configuration as <queue path>/$deadletterqueue

**Comment by NipunaRanasinghe** [comment]
@kapilraajP I see.. even though this can be achieved by asking from the users to append this suffix to the queue name manually, we better have a way to specify this in our connector configs and do this internally instead. 

one option would be to add a field to the receiver/entity configs (preferably an enum?) to specify the subqueue (dead-lettered, differed, etc) and append the suffix based on the user's configs. @kapilraajP WDYT?

**Comment by kapilraajP** [comment]
Yes that is possible to get the type in receiver config and then manipulate according to the the subqueue type provided. Any way user has to initialize seperate receiver client to receive DLQ messages. Shall we go with that approach @NipunaRanasinghe?

**Comment by NipunaRanasinghe** [comment]
> Yes that is possible to get the type in receiver config and then manipulate according to the the subqueue type provided. Any way user has to initialize seperate receiver client to receive DLQ messages. Shall we go with that approach @NipunaRanasinghe?

As per the offline discussion we had, I'm wondering whether we can a new argument to all the `receive()` typed APIs to specify the sub-queue and, handle it in the java level.

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/191
