### ISSUE TITLE
[Task]: Add clean up task to Salesforce bulk tests to recover from test suit intermittent failures

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-extended-library#537]
### Connector Name

module/salesforce (Salesforce)

### Task Description

Time to time Salesforce tests in the bulk API tests are failing due to intermittent reasons. Then the subsequent builds are also failing due to uncleaned entries from the previous tests. Add a new workflow to clean up uncleaned tasks when an intermiiten failure happened.

**Comment by sachinira** [comment]
Failure Reason 1

The Id field inserted in the Bulk insert being an empty string.

Bulk Request
```json
[{"Id":""}, {"Id":"0035g00000zGQaVAAW"}, {"Id":"0035g00000zGQaWAAW"}]
```
Bulk Response
```json
[ {
  "success" : false,
  "created" : false,
  "id" : null,
  "errors" : [ {
    "statusCode" : "INVALID_ID_FIELD",
    "message" : "invalid record id",
    "fields" : [ ]
  } ]
}, {
  "success" : true,
  "created" : false,
  "id" : "0035g00000zGQaVAAW",
  "errors" : [ ]
}, {
  "success" : true,
  "created" : false,
  "id" : "0035g00000zGQaWAAW",
  "errors" : [ ]
} ]
```
