### ISSUE TITLE
[Docs]: can you confirm this sample code (related to salesforce auth config) is correct?

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-extended-library#541]
### Connector Name

connectors/openapi (Open API Connector)

### Documentation Issue/Improvement

<img width="862" alt="image" src="https://github.com/ballerina-platform/ballerina-extended-library/assets/3402882/9068f46e-b05e-43c1-8d36-4f609c1b4a3a">

URL: https://lib.ballerina.io/ballerinax/salesforce/7.5.0

**Comment by NipunaRanasinghe** [comment]
@ramith Currently we are in the process of validating connector samples in all the extended library repos (as a part of https://github.com/ballerina-platform/ballerina-extended-library/issues/539) and, @nipunayf has already updated all the salesforce samples with https://github.com/ballerina-platform/module-ballerinax-sfdc/pull/289.

As per the updated samples above, your code should be updated as shown below.

```ballerina
// Using direct-token config for client configuration
salesforce:ConnectionConfig sfConfig = {
    baseUrl: baseUrl,
    auth: {
        clientId: clientId,
        clientSecret: clientSecret,
        refreshToken: refreshToken,
        refreshUrl: refreshUrl
    }
};

salesforce:Client baseClient = new(sfConfig);
```

**Comment by NipunaRanasinghe** [comment]
Closing as resolved
