### ISSUE TITLE
[Bug]: Detected vulnerable dependencies in the connectors 

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-extended-library#549]
The Trivy scanner has been integrated into the respective modules through https://github.com/ballerina-platform/ballerina-extended-library/issues/536. It has detected vulnerable transitive dependencies in the following modules, which are currently being ignored in the respective repositories. It is necessary to research secure versions for these dependencies and update them accordingly.

- [x] [module-ballerinax-azure-cosmosdb](https://github.com/ballerina-platform/module-ballerinax-azure-cosmosdb)
<img width="1000" alt="image" src="https://github.com/ballerina-platform/ballerina-extended-library/assets/59343084/75814d05-d95a-4233-96f2-b395234d8d62">

- [x] [module-ballerinax-azure-service-bus](https://github.com/ballerina-platform/module-ballerinax-azure-service-bus)
<img width="1057" alt="image" src="https://github.com/ballerina-platform/ballerina-extended-library/assets/59343084/50c25165-d367-40eb-a30e-c01aff606f50">

- [x] [module-ballerinax-cdata.connect](https://github.com/ballerina-platform/module-ballerinax-cdata.connect)
<img width="1000" alt="image" src="https://github.com/ballerina-platform/ballerina-extended-library/assets/59343084/e753dd52-3ca9-41f7-ac06-cd5f6b4f49cd">

- [x] [module-ballerinax-mongodb](https://github.com/ballerina-platform/module-ballerinax-mongodb)
<img width="1000" alt="image" src="https://github.com/ballerina-platform/ballerina-extended-library/assets/59343084/d0b16d55-adca-4d44-bebb-ce2e8d102afd">

**Comment by NipunaRanasinghe** [comment]
Closing with the aforementioned fixes + changes added related to https://github.com/ballerina-platform/ballerina-extended-library/issues/584
