### ISSUE TITLE
[Improvement]: Ballerina `2201.7.1` support for `trigger.shopify`

### ISSUE THREAD

**Issue by chameerar** [ballerina-platform/ballerina-extended-library#557]
### Connector Name

connectors/openapi (Open API Connector)

### Suggested improvement

Ballerina `2201.7.1` support for `trigger.shopify`

### Related issues

I am trying to do create and integration with `trigger.shopify` using Ballerina `2201.7.1` but I'm getting the below error.
```
ERROR [ballerina/cache/3.4.0::cache:(1:1,1:1)] Compilation failed due to an unhandled exception
ERROR [ballerina/http/2.6.1::http_request_context.bal:(88:17,88:41)] invalid return type: members of a dependently-typed union type with an inferred typedesc parameter should have disjoint basic types
```

**Comment by chameerar** [comment]
The issue was resolved after cleaning and rebuilding the project. Closing as no fix is needed.

**Comment by chameerar** [comment]
Reopening as this does not work fine in Choreo.

**Comment by LakshanSS** [comment]
This is released to dev and staging (v1.4.0)

**Comment by chameerar** [comment]
Checked each method form all four Shopify service types and verified working fine.
Checked methods - 
- `onOrdersCreate` in `OrdersService`
- `onProductsCreate` in `ProductsService`
- `onFulfillmentsCreate` in `FulfillmentsService`
- `onCustomersCreate` in `CustomersService`

Log is attached to show successful method invocation. 
<img width="1048" alt="Screenshot 2023-08-22 at 15 28 47" src="https://github.com/ballerina-platform/asyncapi-triggers/assets/96986600/a67a9a57-6a2c-4966-91e7-d9027b3759d8">

**Comment by LakshanSS** [comment]
Closing since this is released to prod as well https://central.ballerina.io/ballerinax/trigger.shopify/1.4.0
