### ISSUE TITLE
[Task]: Remove building examples in Trivy scan workflows.

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-extended-library#584]
### Connector Name

connectors/samples (Connector Samples/Templates)

### Task Description

The Trivy scan should only be performed on Java dependencies introduced by the module itself, and the scan should avoid scanning the dependencies of the Ballerina distribution. Since the example JARs contain dependencies of the Ballerina distribution, they should be excluded from the Trivy scan.

**Comment by aneeshafedo** [comment]
Closing the issue since all the tasks are completed.
