### ISSUE TITLE
[Improvement]: Support update operators other than $set for Mongo DB Connector

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-extended-library#59]
### Connector Name

module/mongodb (Mongo DB)

### Suggested improvement

**Description:**
Following MongoDB update operations are not supported such as $inc, $push, $addToSet

These can be supported by introducing new record for the 
```ballerina
public type UpdateCondition record {
    map<json>? set = ();
    map<json>? inc = ();
    map<json>? push = ();
    map<json>? addToSet = ();
};
public remote function update(UpdateCondition updateCondition, map<json>? filter = (), boolean isMultiple = false, 
                                                                                                boolean upsert = false)
}

```
Above `set` will be UpdateCondition record used when multiple update conditions can be used.

### Related issues

Following MongoDB update operations are not supported such as $inc, $push, $addToSet

**Comment by abeykoon** [comment]
@kasthuriraajan Pls check if this is valid in the new implementation.

**Comment by kasthuriraajan** [comment]
@abeykoon This is not implemented yet. Now `set` is only supported.  Let's do this improvement.

**Comment by abeykoon** [comment]
@kasthuriraajan what is the progress we have made here? 
Is there a PR to be linked?
