### ISSUE TITLE
[Improvement]: Add create repository  operation to GitHub connector

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-extended-library#91]
### Connector Name

module/github (Github)

## Describe your problem(s)
Create repository operation is not implemented under github connector

![Screenshot from 2021-07-02 11-25-46](https://user-images.githubusercontent.com/20430640/124227434-48b61780-db28-11eb-9243-cc43d8054666.png)

## Describe your solution(s)
implement following operations under github connection
- CreateRepository 
- DeleteRepository 

### Related issues

Trying to create a repository using the connector, but could not

**Comment by abeykoon** [comment]
@kasthuriraajan was this captured in the revamp?

**Comment by kasthuriraajan** [comment]
@abeykoon yes it is available in the current version of connector. https://lib.ballerina.io/ballerinax/github/3.0.1/clients/Client#createRepository

**Comment by kasthuriraajan** [comment]
This is implemented.
